# ///// ----- /////

# Compile/transform figma tokens into CSS tokens
name: Compile Figma Tokens

# Controls when the workflow will run
on:
    # Triggers the workflow on 'push' or 'pull request' events but only for the 'main' branch
    push:
      branches: [ main ]

    pull_request:
      branches: [ main ]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    # "ubuntu" is a more generic container
    # using "pandoc/latex" because of dependencies
    # used in the specific "build.sh"
    container: pandoc/latex

    steps:
        - uses: actions/checkout@v2
        - name: creates output
          run:  sh ./build.sh # some command from your repository that creates
                              # output to "source-directory" ("output" in the example)
        - name: Pushes to another repository
          uses: cpina/github-action-push-to-another-repository@main
          env:
            API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
          with:
            source-directory: 'build'
            destination-github-username: 'Visma-Unified-Design'
            destination-repository-name: 'vud-tokens'
            user-email: mihai.baciu@visma.com
            commit-message: 'Update figma tokens compiled to code tokens'
            target-branch: tokens
            target-directory: src/tokens

